### ISSUE TITLE
Function Link::getType() incompatible with Feed Me imports

### ISSUE THREAD

**Issue by luke-underwood** [flipboxfactory/craft-link#11]
Hi! :)

## Issue

I'm encountering issue using this with the [Feed Me plugin](https://plugins.craftcms.com/feed-me). I'm led to believe the issue _might_ be with craft-link.

This error occurs during setup of a feed:

### ArgumentCountError: Too few arguments to function flipbox\craft\link\fields\Link::getType(), 0 passed in /var/www/html/vendor/yiisoft/yii2/base/Component.php on line 232 and exactly 1 expected in /var/www/html/vendor/flipboxfactory/craft-link/src/fields/Link.php:79

<details>
  <summary>Show stacktrace</summary>
  
  ```
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Component.php(232): flipbox\craft\link\fields\Link->getType()
#1 /var/www/html/vendor/yiisoft/yii2/base/Model.php(1015): yii\base\Component->__isset('type')
#2 /var/www/html/vendor/craftcms/feed-me/src/web/twig/variables/FeedMeVariable.php(266): yii\base\Model->offsetExists('type')
#3 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1511): craft\feedme\web\twig\variables\FeedMeVariable->fieldCanBeUniqueId(Object(flipbox\craft\link\fields\Link))
#4 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\feedme\web\twig\variables\FeedMeVariable), 'fieldCanBeUniqu...', Array, 'method', false, false)
#5 /var/www/html/storage/runtime/compiled_templates/78/7852e3edf51b7358966c0681772f36e88958b2aca9c7c3d91ad40d61df5ab8c4.php(100): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\feedme\web\twig\variables\FeedMeVariable), 'fieldCanBeUniqu...', Array, 'method')
#6 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_eed578030f28a95f195aba8c224a2bcd1d5212a35c991d337bfe080facc572f5->block_extraSettings(Array, Array)
#7 /var/www/html/storage/runtime/compiled_templates/8d/8de2e584f9c16b617562fd77908e96154c7406011dcb1bb7b6f435140d128555.php(237): Twig\Template->displayBlock('extraSettings', Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_750157871671d2a15f54268753c577f52b7449456c5187b75c0070c3954d4c17->doDisplay(Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /var/www/html/storage/runtime/compiled_templates/78/7852e3edf51b7358966c0681772f36e88958b2aca9c7c3d91ad40d61df5ab8c4.php(72): Twig\Template->display(Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_eed578030f28a95f195aba8c224a2bcd1d5212a35c991d337bfe080facc572f5->doDisplay(Array, Array)
#12 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /var/www/html/storage/runtime/compiled_templates/2b/2ba4f56649f1fc2ed7007ed26031577a2b1f03fa78b0d714b3a0dd063f2e3829.php(165): Twig\Template->display(Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_fba4e7a8235a91524a5a58f06e8fe8d3b66c39ccca2bd5260211f739c3b9a26a->doDisplay(Array, Array)
#15 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/html/storage/runtime/compiled_templates/15/15c8f247f89fc3e81296f2478a2e22b672a50d421782f332d206780ac11c5e2a.php(169): Twig\Template->display(Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_dd6dcccda727470669de4c8a4eacb9415df997b4dd9dfe349c9a5d38ce0142c9->block_content(Array, Array)
#18 /var/www/html/storage/runtime/compiled_templates/ce/ce4e753099ba22f1a59ea687493a8effe9f11deca542e5ba4b47ae4de27a08ab.php(516): Twig\Template->displayBlock('content', Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_2e7c807f2a77037dfcb11b2aa47080ef2a790499f0e3bb99792d4b9ef6b6205f->block_main(Array, Array)
#20 /var/www/html/storage/runtime/compiled_templates/ce/ce4e753099ba22f1a59ea687493a8effe9f11deca542e5ba4b47ae4de27a08ab.php(334): Twig\Template->displayBlock('main', Array, Array)
#21 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_2e7c807f2a77037dfcb11b2aa47080ef2a790499f0e3bb99792d4b9ef6b6205f->block_body(Array, Array)
#22 /var/www/html/storage/runtime/compiled_templates/98/98ed06c6a9d3aff764c6d483a6169b2137231b0399198fa44a094f7dd678bd5b.php(96): Twig\Template->displayBlock('body', Array, Array)
#23 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_d6227ae51baa379165e7748ec5a309f46db58e13a50d7a65b8c383e83c23623a->doDisplay(Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /var/www/html/storage/runtime/compiled_templates/72/727749b86f98210fa325bb0034470b4955f18bce7a8c1ebd43bd5412fd3b5bd0.php(56): Twig\Template->display(Array, Array)
#26 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_7ba5500440fa2cbc1a281687c70f0ac7298146b24de46100537048f08e01f669->doDisplay(Array, Array)
#27 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /var/www/html/storage/runtime/compiled_templates/ce/ce4e753099ba22f1a59ea687493a8effe9f11deca542e5ba4b47ae4de27a08ab.php(165): Twig\Template->display(Array, Array)
#29 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2e7c807f2a77037dfcb11b2aa47080ef2a790499f0e3bb99792d4b9ef6b6205f->doDisplay(Array, Array)
#30 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#31 /var/www/html/storage/runtime/compiled_templates/3e/3ed1828289be31931f0ca5b7ceacc4493e725c7628639213dee36ef135253924.php(57): Twig\Template->display(Array, Array)
#32 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_10f2909a288aa02f84b0d06d8867724d1c2ef970d6ed6eb564c4e3479c220376->doDisplay(Array, Array)
#33 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#34 /var/www/html/storage/runtime/compiled_templates/15/15c8f247f89fc3e81296f2478a2e22b672a50d421782f332d206780ac11c5e2a.php(79): Twig\Template->display(Array, Array)
#35 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_dd6dcccda727470669de4c8a4eacb9415df997b4dd9dfe349c9a5d38ce0142c9->doDisplay(Array, Array)
#36 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#37 /var/www/html/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#38 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#39 /var/www/html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#40 /var/www/html/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('feed-me/feeds/_...', Array)
#41 /var/www/html/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('feed-me/feeds/_...', Array)
#42 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('feed-me/feeds/_...', Array, 'cp')
#43 /var/www/html/vendor/craftcms/feed-me/src/controllers/FeedsController.php(104): craft\web\Controller->renderTemplate('feed-me/feeds/_...', Array)
#44 [internal function]: craft\feedme\controllers\FeedsController->actionMapFeed('1', NULL)
#45 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#46 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#47 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('map-feed', Array)
#48 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('map-feed', Array)
#49 /var/www/html/vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('feed-me/feeds/m...', Array)
#50 /var/www/html/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('feed-me/feeds/m...', Array)
#51 /var/www/html/vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request))
#52 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#53 /var/www/html/web/index.php(21): yii\base\Application->run()
#54 {main}
  ```
</details>

## Cause
`Link::getType()` requires an identifier parameter. This is inconsistent with native Craft fields or other custom plugin fields I've seen, where no parameter is required in order to return a TypeInterface. I haven't looked through all source code but I'm sure there's a good reason craft-link requires this. 

```
/**
  * @param string $identifier
  * @return TypeInterface|null
  * @throws \yii\base\InvalidConfigException
  */
public function getType(string $identifier)
{
    // Is it already an object?
    if (!array_key_exists($identifier, $this->types)) {
        // Can we create it?
        if (!$type = $this->createFromConfig($identifier)) {
            return null;
        }

        $this->types[$identifier] = $type;
    }

    return clone $this->types[$identifier];
}
```

## Solution
Feed Me works correctly when`$identifier` is optional, and returns null if not set. I'm unsure this is the right solution, or the effect this has on the plugin...

```diff
/**
  * @param string $identifier
  * @return TypeInterface|null
  * @throws \yii\base\InvalidConfigException
  */
-public function getType(string $identifier)
+public function getType(string $identifier = null)
{
+    if ($identifier === null) return null;
    // Is it already an object?
    if (!array_key_exists($identifier, $this->types)) {
        // Can we create it?
        if (!$type = $this->createFromConfig($identifier)) {
            return null;
        }

        $this->types[$identifier] = $type;
    }

    return clone $this->types[$identifier];
}
```

## Versions

|Application info|Version|
|-|-|
|Craft edition & version|Craft Pro 3.7.13|
|PHP version | 7.4.23|
|Linux|5.10.47-linuxkit|
|Yii version|2.0.43|

|Plugin|Version|
|-|-|
|Feed Me|4.4.0|
|Link|1.1.4|

**Comment by nateiler** [comment]
The `$identifier` is a randomly generated string; which is used to support multiple of the same link type (but with different configurations).  As a result, I can see how this becomes difficult to identify a link type dynamically (via an import, etc).

The suggested work around appears to omit a link field during import;  I assume the data you are importing does not contain any link data.
